### PR TITLE
Support universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by andialbrecht** [comment]
Thanks!

**Comment by timgraham** [comment]
sqlparse doesn't seem to support universal wheels. Creating a wheel on Python 2 causes this traceback on Python 3:
```
   from sqlparse import lexer
  File "/home/tim/.virtualenvs/django343/lib/python3.4/site-packages/sqlparse/lexer.py", line 84
    except Exception, err:
                    ^
SyntaxError: invalid syntax
```
Creating the wheel on Python 3, results in this exception on Python 2:
```
Compiling /tmp/pip-qYhOhj-build/sqlparse/lexer.py ...
  File "/tmp/pip-qYhOhj-build/sqlparse/lexer.py", line 156
    class Lexer(object, metaclass=LexerMeta):
                                 ^
SyntaxError: invalid syntax
```
sqlparse 0.1.17 broke Django's CI due to this. Let me know if you need help. For now, I think we could just revert this addition.

**Comment by graingert** [comment]
Ah you're right this project uses 2to3 yeah wheel support won't work

**Comment by timgraham** [comment]
Thanks for confirming. PR to revert: https://github.com/andialbrecht/sqlparse/pull/203

**Pull request merged**
