### PR TITLE
Add RETURNING keyword

### PR DESCRIPTION
**Pull request by darikg**
Postgresql has a keyword `RETURNING` used in insert/update/delete commands

### CODE REVIEW

**Comment by darikg** [comment]
Took me a couple tries to get this right bc I kept screwing up alphabetical order :stuck_out_tongue_closed_eyes:

**Comment by vmuriart** [comment]
scared me for a minute with that 1.22% coverage drop. 
I'm not familiar with Postgresql, any concerns or possibility of `returning(...)` to be parsed as a function? I'm not even sure if that's valid syntax on postgresql

**Comment by darikg** [comment]
It doesn't use function syntax. It looks like this:

`INSERT INTO foo (x, y) VALUES (1, 2, 3) RETURNING x, z`
or `DELETE FROM foo WHERE bar > 3 RETURNING baz, qux`

**Comment by vmuriart** [comment]
cool, just wanted to check. thanks! - i merged the pr

**Pull request merged**
