### PR TITLE
Add high-level function to parse column names and types in CREATE TABLE statements

### PR DESCRIPTION
**Pull request by AndiDog**
Usage:

``` python
from sqlparse import lexer
from sqlparse.functions import get_create_table_info
from pprint import pprint
pprint(get_create_table_info(lexer.tokenize('''
    CREATE TABLE customer (
        id BIGINT PRIMARY KEY NOT NULL,
        name VARCHAR(255) NOT NULL,
        address TEXT NULL
    )
''')))
```

prints:

```
[('customer',
    {0: ('id', 'BIGINT', 'NOT NULL'),
     1: ('name', 'VARCHAR', 'NOT NULL'),
     2: ('address', 'TEXT', 'NULL')})]
```

### CODE REVIEW

**Comment by AndiDog** [comment]
@andialbrecht: Are you planning to integrate this?

**Comment by andialbrecht** [comment]
uhm, yes... sorry I've lost this from my radar. I'll have a look at the weekend or next week.

**Comment by vmuriart** [comment]
Morning @AndiDog. I started reviewing the `pr` and [rebased it](https://github.com/vmuriart/sqlparse/tree/rb-parse-create-table) to make it easier to merge in. I updated parts of the code to the current code base but I haven't been able to get it running yet. 
If you get a chance please take a look to see what is missing to get it running.

On a separate note, when I was trying to debug the code I noticed that the filter was one long (complex) function. Any chance you can break it down into smaller steps?

**Comment by vmuriart** [comment]
ha! found my mistake, and now it's [working](https://travis-ci.org/vmuriart/sqlparse/builds/135759166) on Python 2.6, 2.7 and pypy. 

The branch I [mentioned earlier](https://github.com/vmuriart/sqlparse/tree/rb-parse-create-table) is rebased to master, and with the current structure we shouldn't have any more merge conflicts on it. 

I added some [comments](https://github.com/vmuriart/sqlparse/commit/4f89efaace999e3c885c9bfc131e93740eb7c016) to help it pass for python 3.3+.

**Comment by AndiDog** [comment]
I don't seem to find the time to continue on this. If someone wants to take it up and integrate this parsing feature, please go ahead ;)

**Pull request closed without merging**
