### PR TITLE
fix column definition parsing for create table statement

### PR DESCRIPTION
**Pull request by clin7**
- Excluded the comma in the column definition token list when parsing column definitions; also stopped processing column attributes if it reaches the end of the definition
- Added exceptions when the column type cannot be found.
- Added tests for new changes

### CODE REVIEW

**Comment by andialbrecht** [comment]
Hey @clin7,

out of interest, why did you close the pull request?

**Comment by clin7** [comment]
Hi Andi,

I'm sorry that I pulled the wrong request. Is there a way that I can
discard it?

Thanks,
Chia-chi

**Comment by andialbrecht** [comment]
AFAIK there's no way to *delete* a pull request. By closing it you've actually discarded it.

**Comment by clin7** [comment]
Thanks Andi! I've closed the request. :)

Chia-chi

**Pull request closed without merging**
